version: '3'
services:
  mymysql:
    image: "mysql:8.0.13"
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: "twitter2"
      MYSQL_ROOT_PASSWORD: "secret"
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
  web:
    build: .
    depends_on:
      - mymysql
    ports:
      - "80:8080"

volumes:
  mysql_data: